version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWUSER: ${WWWUSER}
        volumes:
            - '.:/var/www/web/sites/app'
        networks:
            - app_network
        extra_hosts:
            - "${APP_DOMAIN:-localhost}:172.17.0.1"
        depends_on:
            - mysql
            - redis
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - ${APP_PORT:-80}:80
            - ${APP_HTTPS_PORT:-443}:443
        volumes:
            - .:/var/www/web/sites/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/ssl/enabled/certs/localhost.crt:/etc/ssl/certs/localhost.crt
            - ./docker/ssl/enabled/private/localhost.key:/etc/ssl/private/localhost.key
        depends_on:
            - app
        networks:
            - app_network
    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'app_mysql_volume:/var/lib/mysql'
        networks:
            - app_network
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'app_redis_volume:/data'
        networks:
            - app_network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 15000M
        restart: always
        ports:
            - '${PHPMYADMIN_PORT:-8081}:80'
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
volumes:
    app_mysql_volume:
        driver: local
    app_redis_volume:
        driver: local
